#!/bin/bash
if test -z "$DBUS_SESSION_BUS_ADDRESS"; then
    eval `dbus-launch --sh-syntax --exit-with-session`
fi
# compiz --replace ccp >> /tmp/compiz.log & wmpid=$!
R600_DEBUG=sbsafemath compiz --replace ccp &> /tmp/compiz.log & wmpid=$!
sleep 1
if [ -f ~/.compiz-session ]; then
    source ~/.compiz-session &
else
    xterm &
fi
# Wait for WM
wait $wmpid

